# Site settings
title: "Nikola Milić"
description: "deltakroneker"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nikola Milić"
resume_title:                   "Junior iOS Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nikola.milic.ios@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+381 616352244"
resume_contact_address:         "Ratnih vojnih invalida 3, Borča"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hey there, I’m Nikola - a student at the University of Belgrade, School of Electrical Engineering. I am a fan of technology, programming and music. I also love healthy lifestyle, running and dancing. </p><p>On this website i will show you all the apps and designs i made. </br> If you need an iOS app made, whether it be big business project or just simple personal idea, it can be done. </br> Want to know how much that will cost? Feel free to contact me and we can arrange a deal. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/deltakroneker"
  resume_facebook_url:          "https://www.facebook.com/omgzomg"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://instagram.com/deltakroneker"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
