# Site settings
title: "Nikola Milić"
description: "deltakroneker"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nikola Milić"
resume_title:                   "Junior iOS Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nikola.milic.ios@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+381 616352244"
resume_contact_address:         "Ratnih vojnih invalida 3, Borča"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi, my name is Nikola, I am student & mobile app developer. My experience consists of personal projects, freelance work and full time job as iOS developer. My aim is to make apps that are easy to use, read, and modify. </br> These three points contribute in easily maintainable project so you can enhance an app as your company grows. </br></br> ✅ iOS Apps made in Swift & Xcode </br> ⚛️ UX/UI Consulting</br> ✴️ Professional communication </br> 💯 Percent satisfaction </br></br> Feel free to contact me and ask anything!  </br></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/deltakroneker"
  resume_facebook_url:          "https://www.facebook.com/omgzomg"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://instagram.com/deltakroneker"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
